<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="arm_base_length" value="0.1" />
  <xacro:property name="arm_base_width" value="0.1" />
  <xacro:property name="arm_base_height" value="0.02" />
  <xacro:property name="fore_arm_length" value="0.3" />
  <xacro:property name="fore_arm_radius" value="0.02" />
  <xacro:property name="hand_length" value="0.3" />
  <xacro:property name="hand_radius" value="0.02" />



  <link name="arm_base_link">
    <visual>
      <geometry>
        <box size="${arm_base_width} ${arm_base_length} ${arm_base_height}"/>
      </geometry>
      <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <box size="${arm_base_width} ${arm_base_length} ${arm_base_height}"/>
      </geometry>
      <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
    </collision>
    <xacro:box_inertia  
        m="0.5"  
        x="${arm_base_width}"  
        y="${arm_base_length}"  
        z="${arm_base_height}"  
        o_xyz="0 0 ${arm_base_height/2}"  
        o_rpy="0 0 0" />
  </link>

  <joint name="joint0" type="revolute">
    <origin xyz="0.0 0.0 ${arm_base_height}" rpy="0.0 0.0 0.0"/>
    <parent link="arm_base_link"/>
    <child link="fore_arm_link"/>
    <axis xyz="0.0 1.0 0.0"/>
    <limit lower="0.0" upper="1.57" effort="100.0" velocity="100.0"/>
    <dynamics damping="0.3" friction="0.3"/>
  </joint>

  <link name="fore_arm_link">
    <visual>
      <geometry>
        <cylinder length="${fore_arm_length}" radius="${fore_arm_radius}"/>
      </geometry>
      <origin xyz="0 0 ${fore_arm_length/2}" rpy="0 0 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${fore_arm_length}" radius="${fore_arm_radius}"/>
      </geometry>
      <origin xyz="0 0 ${fore_arm_length/2}" rpy="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia  
        m="0.3"  
        r="${fore_arm_radius}"  
        h="${fore_arm_length}"  
        o_xyz="0 0 ${fore_arm_length/2}"  
        o_rpy="0 0 0" />
  </link>

  <joint name="joint1" type="revolute">
    <origin xyz="0.0 0.0 ${fore_arm_length}" rpy="0.0 0.0 0.0"/>
    <parent link="fore_arm_link"/>
    <child link="hand_link"/>
    <axis xyz="0.0 1.0 0.0"/>
    <limit lower="0" upper="1.57" effort="100.0" velocity="100.0"/>
    <dynamics damping="0.3" friction="0.3"/>
  </joint>

  <link name="hand_link">
    <visual>
      <geometry>
        <cylinder length="${hand_length}" radius="${hand_radius}"/>
      </geometry>
      <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0"/>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${hand_length}" radius="${hand_radius}"/>
      </geometry>
      <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0"/>
    </collision>
    <xacro:cylinder_inertia  
        m="0.1"  
        r="${hand_radius}"  
        h="${hand_length}"  
        o_xyz="0 0 ${hand_length/2}"  
        o_rpy="0 0 0" />
  </link>

  


</robot>
